In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.datasets as datasets
import torchvision.transforms as transforms
import matplotlib.pyplot as plt 
import io
import sys
import os

In [2]:
EPOCH = 100
BATCH_SIZE = 64
LR = 0.001

In [3]:
T = transforms.ToTensor()
train_data = datasets.CIFAR10(root='~/dataset/', train=True,transform=T,download=True)
test_data =datasets.CIFAR10(root='~/dataset/',train=False,transform=T,download=True)

Files already downloaded and verified
Files already downloaded and verified


In [4]:
sys.path.append('..')
from alexnet import alexnet
from resnet_50 import resnet_50
from torch.utils.data import DataLoader
from torchvision.models import AlexNet_Weights
from torchvision.models import ResNet50_Weights
train_loader = DataLoader(dataset=train_data,batch_size=BATCH_SIZE,shuffle=True,num_workers=2)
test_loader = DataLoader(dataset=test_data,batch_size=BATCH_SIZE,shuffle=True,num_workers=2)
model = resnet_50(weights = ResNet50_Weights.IMAGENET1K_V1)

In [5]:
test_train = train_data[0][0]

In [6]:
test_train = torch.unsqueeze(test_train,0)

In [7]:
test_train = test_train.cuda()


In [8]:
model = model.cuda()

In [9]:
model = model.eval()

In [10]:
# res = model(test_train)

In [11]:
test_train

tensor([[[[0.2314, 0.1686, 0.1961,  ..., 0.6196, 0.5961, 0.5804],
          [0.0627, 0.0000, 0.0706,  ..., 0.4824, 0.4667, 0.4784],
          [0.0980, 0.0627, 0.1922,  ..., 0.4627, 0.4706, 0.4275],
          ...,
          [0.8157, 0.7882, 0.7765,  ..., 0.6275, 0.2196, 0.2078],
          [0.7059, 0.6784, 0.7294,  ..., 0.7216, 0.3804, 0.3255],
          [0.6941, 0.6588, 0.7020,  ..., 0.8471, 0.5922, 0.4824]],

         [[0.2431, 0.1804, 0.1882,  ..., 0.5176, 0.4902, 0.4863],
          [0.0784, 0.0000, 0.0314,  ..., 0.3451, 0.3255, 0.3412],
          [0.0941, 0.0275, 0.1059,  ..., 0.3294, 0.3294, 0.2863],
          ...,
          [0.6667, 0.6000, 0.6314,  ..., 0.5216, 0.1216, 0.1333],
          [0.5451, 0.4824, 0.5647,  ..., 0.5804, 0.2431, 0.2078],
          [0.5647, 0.5059, 0.5569,  ..., 0.7216, 0.4627, 0.3608]],

         [[0.2471, 0.1765, 0.1686,  ..., 0.4235, 0.4000, 0.4039],
          [0.0784, 0.0000, 0.0000,  ..., 0.2157, 0.1961, 0.2235],
          [0.0824, 0.0000, 0.0314,  ..., 0

In [12]:
a = test_train.clone()

In [13]:
b = train_data[1][0]

In [14]:
a

tensor([[[[0.2314, 0.1686, 0.1961,  ..., 0.6196, 0.5961, 0.5804],
          [0.0627, 0.0000, 0.0706,  ..., 0.4824, 0.4667, 0.4784],
          [0.0980, 0.0627, 0.1922,  ..., 0.4627, 0.4706, 0.4275],
          ...,
          [0.8157, 0.7882, 0.7765,  ..., 0.6275, 0.2196, 0.2078],
          [0.7059, 0.6784, 0.7294,  ..., 0.7216, 0.3804, 0.3255],
          [0.6941, 0.6588, 0.7020,  ..., 0.8471, 0.5922, 0.4824]],

         [[0.2431, 0.1804, 0.1882,  ..., 0.5176, 0.4902, 0.4863],
          [0.0784, 0.0000, 0.0314,  ..., 0.3451, 0.3255, 0.3412],
          [0.0941, 0.0275, 0.1059,  ..., 0.3294, 0.3294, 0.2863],
          ...,
          [0.6667, 0.6000, 0.6314,  ..., 0.5216, 0.1216, 0.1333],
          [0.5451, 0.4824, 0.5647,  ..., 0.5804, 0.2431, 0.2078],
          [0.5647, 0.5059, 0.5569,  ..., 0.7216, 0.4627, 0.3608]],

         [[0.2471, 0.1765, 0.1686,  ..., 0.4235, 0.4000, 0.4039],
          [0.0784, 0.0000, 0.0000,  ..., 0.2157, 0.1961, 0.2235],
          [0.0824, 0.0000, 0.0314,  ..., 0

In [15]:
b = torch.unsqueeze(b,0)

In [16]:
b = b.cuda()

In [17]:
a-b

tensor([[[[-0.3725, -0.3255, -0.2157,  ...,  0.2627,  0.2549,  0.2706],
          [-0.4863, -0.5686, -0.4196,  ...,  0.1059,  0.1647,  0.2000],
          [-0.4510, -0.4824, -0.2588,  ...,  0.1529,  0.2039,  0.1647],
          ...,
          [ 0.1294,  0.1765,  0.1725,  ...,  0.4627, -0.0196, -0.1569],
          [ 0.0588,  0.0667,  0.1059,  ...,  0.3176, -0.1020, -0.1882],
          [ 0.0549,  0.0392,  0.0627,  ...,  0.2863,  0.0314, -0.0784]],

         [[-0.4510, -0.3569, -0.2196,  ...,  0.1451,  0.1373,  0.1686],
          [-0.5490, -0.6000, -0.4588,  ..., -0.0431,  0.0118,  0.0549],
          [-0.5137, -0.5451, -0.3451,  ...,  0.0078,  0.0549,  0.0157],
          ...,
          [ 0.0118, -0.0039,  0.0039,  ...,  0.3882, -0.0863, -0.1922],
          [-0.0588, -0.1137, -0.0667,  ...,  0.2157, -0.2039, -0.2667],
          [-0.0157, -0.0745, -0.0549,  ...,  0.2000, -0.0627, -0.1608]],

         [[-0.4863, -0.3569, -0.2039,  ...,  0.1451,  0.1216,  0.1294],
          [-0.5843, -0.6039, -

In [18]:
a*b

tensor([[[[0.1397, 0.0833, 0.0807,  ..., 0.2211, 0.2034, 0.1798],
          [0.0344, 0.0000, 0.0346,  ..., 0.1816, 0.1409, 0.1332],
          [0.0538, 0.0342, 0.0867,  ..., 0.1434, 0.1255, 0.1123],
          ...,
          [0.5598, 0.4822, 0.4689,  ..., 0.1033, 0.0525, 0.0758],
          [0.4567, 0.4150, 0.4548,  ..., 0.2915, 0.1835, 0.1672],
          [0.4437, 0.4082, 0.4487,  ..., 0.4750, 0.3321, 0.2705]],

         [[0.1688, 0.0969, 0.0768,  ..., 0.1928, 0.1730, 0.1545],
          [0.0492, 0.0000, 0.0154,  ..., 0.1340, 0.1021, 0.0977],
          [0.0572, 0.0157, 0.0478,  ..., 0.1059, 0.0904, 0.0775],
          ...,
          [0.4366, 0.3624, 0.3962,  ..., 0.0695, 0.0253, 0.0434],
          [0.3292, 0.2875, 0.3565,  ..., 0.2117, 0.1087, 0.0986],
          [0.3278, 0.2936, 0.3407,  ..., 0.3763, 0.2432, 0.1882]],

         [[0.1812, 0.0941, 0.0628,  ..., 0.1179, 0.1114, 0.1109],
          [0.0520, 0.0000, 0.0000,  ..., 0.0660, 0.0477, 0.0535],
          [0.0530, 0.0000, 0.0138,  ..., 0

In [19]:
from torchvision.models import resnet34
from torchvision.models import ResNet34_Weights
m = resnet34(weights = ResNet34_Weights.IMAGENET1K_V1)

In [20]:
m = m.cuda()

In [21]:
m(a)

: 

: 